
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.View;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author khalifardy
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    DefaultTableModel tabel_produk;
    public ArrayList<Integer> lstid = new ArrayList<>();
    public int ind ;
    private static JFrame runningInstance;
    public JFrame() {
        initComponents();
        String [] header = {"no", "nama", "harga","stok"};
        tabel_produk = new DefaultTableModel(header,0);
        tabelproduk.setModel(tabel_produk);
        show_tablebarang();
        tabelproduk.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                // Check if the selection is adjusting (to avoid firing the event twice)
                if (!e.getValueIsAdjusting()) {
                    int selectedRow = tabelproduk.getSelectedRow();
                    if (selectedRow != -1) {  // Check if a row is actually selected
                        ind = selectedRow;
                    }
                }
            }
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tambahdialog = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        namafield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spinerharga = new javax.swing.JSpinner();
        spinnerstok = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        simpanbutton = new javax.swing.JButton();
        ubahdialog = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nameubahfield = new javax.swing.JTextField();
        spinnerubahharga = new javax.swing.JSpinner();
        spinnerubahstok = new javax.swing.JSpinner();
        simpanUbahbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tambahbutton = new javax.swing.JButton();
        ubahbutton = new javax.swing.JButton();
        hapusbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelproduk = new javax.swing.JTable();

        tambahdialog.setMinimumSize(new java.awt.Dimension(600, 400));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setText("Form Tambah Produk");

        jLabel3.setText("Nama");

        jLabel4.setText("Harga");

        jLabel5.setText("Stok");

        simpanbutton.setText("Simpan");
        simpanbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tambahdialogLayout = new javax.swing.GroupLayout(tambahdialog.getContentPane());
        tambahdialog.getContentPane().setLayout(tambahdialogLayout);
        tambahdialogLayout.setHorizontalGroup(
            tambahdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahdialogLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(tambahdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(64, 64, 64)
                .addGroup(tambahdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namafield, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(spinerharga)
                    .addComponent(spinnerstok))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahdialogLayout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(tambahdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahdialogLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(180, 180, 180))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahdialogLayout.createSequentialGroup()
                        .addComponent(simpanbutton)
                        .addGap(241, 241, 241))))
        );
        tambahdialogLayout.setVerticalGroup(
            tambahdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahdialogLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(tambahdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namafield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(tambahdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spinerharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(tambahdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spinnerstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(simpanbutton)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        ubahdialog.setMinimumSize(new java.awt.Dimension(500, 400));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setText("Form Ubah Produk");

        jLabel7.setText("Nama");

        jLabel8.setText("Harga");

        jLabel9.setText("stok");

        simpanUbahbutton.setText("Simpan");
        simpanUbahbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanUbahbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ubahdialogLayout = new javax.swing.GroupLayout(ubahdialog.getContentPane());
        ubahdialog.getContentPane().setLayout(ubahdialogLayout);
        ubahdialogLayout.setHorizontalGroup(
            ubahdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ubahdialogLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(ubahdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(ubahdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(nameubahfield, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(spinnerubahharga)
                    .addComponent(spinnerubahstok))
                .addGap(120, 120, 120))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ubahdialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(simpanUbahbutton)
                .addGap(207, 207, 207))
        );
        ubahdialogLayout.setVerticalGroup(
            ubahdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ubahdialogLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(ubahdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nameubahfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(ubahdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(spinnerubahharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(ubahdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(spinnerubahstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(simpanUbahbutton)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setText("Daftar Produk");

        tambahbutton.setText("Tambah");
        tambahbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahbuttonActionPerformed(evt);
            }
        });

        ubahbutton.setText("Ubah");
        ubahbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahbuttonActionPerformed(evt);
            }
        });

        hapusbutton.setText("Hapus");
        hapusbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusbuttonActionPerformed(evt);
            }
        });

        tabelproduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Harga", "Stok"
            }
        ));
        jScrollPane1.setViewportView(tabelproduk);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tambahbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ubahbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tambahbutton)
                        .addGap(28, 28, 28)
                        .addComponent(ubahbutton)
                        .addGap(35, 35, 35)
                        .addComponent(hapusbutton)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void show_tablebarang() {
    int row = tabel_produk.getRowCount();
    
    // Remove all rows from the table model
    for (int i = row - 1; i >= 0; i--) {
        tabel_produk.removeRow(i);
    }
    
    try {
        Database db = new Database();
        String sql = "select * from tabel_produk";
        ResultSet rs = db.getData(sql);
        int count = 1;
        while (rs.next()) {
            System.out.println(rs.getString("nama"));
            String data[] = {String.valueOf(count), rs.getString("nama"),
                rs.getString("harga"),
                rs.getString("stok")};
            tabel_produk.addRow(data);
            this.lstid.add(rs.getInt("id"));
            count ++;
        }
    } catch (SQLException ex) {
        Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
}
    public static void setRunningInstance(JFrame instance) {
        runningInstance = instance;
    }
    
    public static void closeRunningInstance() {
        if (runningInstance != null) {
            runningInstance.dispose();
        }
    }
    
    public static void showMainFrame() {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                JFrame utama = new JFrame();
                setRunningInstance(utama);
                utama.setVisible(true);
            }
        });
    }
   
   public void closeMainFrame() {
        dispose(); // Close the main frame
    }
    private void tambahbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahbuttonActionPerformed
        // TODO add your handling code here:

      tambahdialog.setVisible(true);
    }//GEN-LAST:event_tambahbuttonActionPerformed

    private void ubahbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahbuttonActionPerformed
        // TODO add your handling code here:
        try {
        Database db = new Database();
        String sql = "SELECT * FROM tabel_produk WHERE id = "+ this.lstid.get(this.ind);
        ResultSet rs = db.getData(sql);
        if(rs.next()){
            nameubahfield.setText(rs.getString("nama"));
            spinnerubahharga.setValue(rs.getInt("harga"));
            spinnerubahstok.setValue(rs.getInt("stok"));
        };
        
        ubahdialog.setVisible(true);
    
        
    } catch (SQLException ex) {
        Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_ubahbuttonActionPerformed

    private void simpanbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanbuttonActionPerformed
        // TODO add your handling code here:
        try {
        Database db = new Database();
        Produk obj = new Produk(namafield.getText(),(Integer)spinerharga.getValue(),(Integer)spinnerstok.getValue());
        obj.insert_produk();
        JOptionPane.showMessageDialog(null,"produk berhasil ditambahkan");
        tambahdialog.setVisible(false);
        JFrame.closeRunningInstance();
        dispose();
        JFrame.showMainFrame();
        
    } catch (SQLException ex) {
        Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_simpanbuttonActionPerformed

    private void simpanUbahbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanUbahbuttonActionPerformed
        // TODO add your handling code here:
         try {
        Database db = new Database();
        String sql = "UPDATE tabel_produk SET nama=?, harga=?, stok=? WHERE id=?";
        db.query_update(sql, nameubahfield.getText(), (Integer)spinnerubahharga.getValue(), (Integer)spinnerubahstok.getValue(), this.lstid.get(this.ind));
        JOptionPane.showMessageDialog(null,"produk berhasil dirubah");
        ubahdialog.setVisible(false);
        JFrame.closeRunningInstance();
        dispose();
        JFrame.showMainFrame();
        
    } catch (SQLException ex) {
        Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_simpanUbahbuttonActionPerformed

    private void hapusbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusbuttonActionPerformed
        // TODO add your handling code here:
        Database db;
        try {
            db = new Database();
            
            String sql = "DELETE FROM tabel_produk WHERE id = ?";
      
            db.query_delete(sql,this.lstid.get(this.ind));
            JOptionPane.showMessageDialog(null,"produk berhasil dihapus");
            JFrame.closeRunningInstance();
            dispose();
            JFrame.showMainFrame();
            
           
        } catch (SQLException ex) {
            Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hapusbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame utama = new JFrame();
                setRunningInstance(utama);
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapusbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namafield;
    private javax.swing.JTextField nameubahfield;
    private javax.swing.JButton simpanUbahbutton;
    private javax.swing.JButton simpanbutton;
    private javax.swing.JSpinner spinerharga;
    private javax.swing.JSpinner spinnerstok;
    private javax.swing.JSpinner spinnerubahharga;
    private javax.swing.JSpinner spinnerubahstok;
    private javax.swing.JTable tabelproduk;
    private javax.swing.JButton tambahbutton;
    private javax.swing.JDialog tambahdialog;
    private javax.swing.JButton ubahbutton;
    private javax.swing.JDialog ubahdialog;
    // End of variables declaration//GEN-END:variables
}
