/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author khalifardy
 */
import java.util.logging.Level;
import java.util.logging.Logger;

import java.sql.*;
import javax.swing.JOptionPane;

import javax.swing.text.View;
public class Jframe2 extends javax.swing.JFrame {

    private final String nim;
    public int id;

    /**
     * Creates new form Jframe2
     */
   
    public Jframe2(String NIM) {
        initComponents();
        this.nim = NIM;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel8dialog = new javax.swing.JLabel();
        NIMfielddialog = new javax.swing.JTextField();
        namafielddialog = new javax.swing.JTextField();
        jLabel9dialog = new javax.swing.JLabel();
        jLabel10dialog = new javax.swing.JLabel();
        ifbuttondialog = new javax.swing.JRadioButton();
        sebuttondialog = new javax.swing.JRadioButton();
        dsbuttondialog = new javax.swing.JRadioButton();
        itbuttondialog = new javax.swing.JRadioButton();
        savebuttondialog = new javax.swing.JButton();
        editbutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();

        jDialog1.setMinimumSize(new java.awt.Dimension(400, 400));

        jLabel8dialog.setText("NIM");

        NIMfielddialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIMfielddialogActionPerformed(evt);
            }
        });

        namafielddialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namafielddialogActionPerformed(evt);
            }
        });

        jLabel9dialog.setText("NAMA");

        jLabel10dialog.setText("Prodi");

        ifbuttondialog.setText("IF");
        ifbuttondialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ifbuttondialogActionPerformed(evt);
            }
        });

        sebuttondialog.setText("SE");
        sebuttondialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sebuttondialogActionPerformed(evt);
            }
        });

        dsbuttondialog.setText("DS");
        dsbuttondialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsbuttondialogActionPerformed(evt);
            }
        });

        itbuttondialog.setText("IT");
        itbuttondialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itbuttondialogActionPerformed(evt);
            }
        });

        savebuttondialog.setText("SImpan");
        savebuttondialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttondialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8dialog)
                    .addComponent(jLabel9dialog)
                    .addComponent(jLabel10dialog))
                .addGap(62, 62, 62)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(savebuttondialog)
                    .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(NIMfielddialog)
                        .addComponent(namafielddialog, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ifbuttondialog)
                            .addComponent(itbuttondialog))
                        .addGap(33, 33, 33)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dsbuttondialog)
                            .addComponent(sebuttondialog))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8dialog)
                    .addComponent(NIMfielddialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9dialog)
                    .addComponent(namafielddialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10dialog)
                    .addComponent(ifbuttondialog)
                    .addComponent(sebuttondialog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itbuttondialog)
                    .addComponent(dsbuttondialog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(savebuttondialog)
                .addGap(52, 52, 52))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editbutton.setText("Edit");
        editbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbuttonActionPerformed(evt);
            }
        });

        deletebutton.setText("delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(editbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(deletebutton)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editbutton)
                    .addComponent(deletebutton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbuttonActionPerformed
        // TODO add your handling code here:
        try{
            Database db = new Database();
            String sql = "select * from tabel_mahasiswa where nim = "+this.nim;
            ResultSet rs = db.getData(sql);
            if (rs.next()){
                namafielddialog.setText(rs.getString("nama"));
                NIMfielddialog.setText(rs.getString("nim"));
                if("IF".equals(rs.getString("prodi"))) {
                    ifbuttondialog.setSelected(true);
                }else if ("IT".equals(rs.getString("prodi"))) {
                    itbuttondialog.setSelected(true);
                }else if ("SE".equals(rs.getString("prodi"))) {
                    sebuttondialog.setSelected(true);
                }else {
                    dsbuttondialog.setSelected(true);
                };
                this.id = rs.getInt("id"); 
                System.out.println(this.id);
            };
               
        }catch (SQLException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        };
        jDialog1.setVisible(true);
        
    }//GEN-LAST:event_editbuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // TODO add your handling code here:
        Database db;
        try {
            db = new Database();
            String sql2 = "select * from tabel_mahasiswa where nim = "+this.nim;
            ResultSet rs = db.getData(sql2);
            if (rs.next()){
                this.id = rs.getInt("id"); 
                System.out.println(this.id);
            };
            String sql = "DELETE FROM tabel_mahasiswa WHERE id = ?";
      
            db.query_delete(sql,this.id);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Jframe2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void namafielddialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namafielddialogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namafielddialogActionPerformed

    private void ifbuttondialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ifbuttondialogActionPerformed
        // TODO add your handling code here:
        if (ifbuttondialog.isSelected()){
            dsbuttondialog.setSelected(false);
            itbuttondialog.setSelected(false);
            sebuttondialog.setSelected(false);
        }
    }//GEN-LAST:event_ifbuttondialogActionPerformed

    private void sebuttondialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sebuttondialogActionPerformed
        // TODO add your handling code here:
        if (sebuttondialog.isSelected()){
            dsbuttondialog.setSelected(false);
            itbuttondialog.setSelected(false);
            ifbuttondialog.setSelected(false);
        }
    }//GEN-LAST:event_sebuttondialogActionPerformed

    private void dsbuttondialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsbuttondialogActionPerformed
        // TODO add your handling code here:
        if (dsbuttondialog.isSelected()){
            ifbuttondialog.setSelected(false);
            itbuttondialog.setSelected(false);
            sebuttondialog.setSelected(false);
        }
    }//GEN-LAST:event_dsbuttondialogActionPerformed

    private void itbuttondialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itbuttondialogActionPerformed
        // TODO add your handling code here:
        if (itbuttondialog.isSelected()){
            dsbuttondialog.setSelected(false);
            ifbuttondialog.setSelected(false);
            sebuttondialog.setSelected(false);
        }
    }//GEN-LAST:event_itbuttondialogActionPerformed

    private void savebuttondialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttondialogActionPerformed
        // TODO add your handling code here:
        String prodi="";
        if (ifbuttondialog.isSelected()){
            prodi = ifbuttondialog.getText();
        };

        if (itbuttondialog.isSelected()){
            prodi = itbuttondialog.getText();
        };

        if (sebuttondialog.isSelected()){
            prodi = sebuttondialog.getText();
        };
        
        if (dsbuttondialog.isSelected()){
            prodi = dsbuttondialog.getText();
        };

       
       String nama = namafielddialog.getText();
       String nim = NIMfielddialog.getText();
        try{
                Database db = new Database();
                String sql = "UPDATE tabel_mahasiswa SET nama=?, nim=?, prodi=? WHERE id=?";
                
                db.query_update(sql,nama,nim,prodi,this.id);
                db.closeConn();
                      
            }
            catch(SQLException ex){
                Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null,"Mahasiswa berhasil diupdate");
            namafielddialog.setText("");
            NIMfielddialog.setText("");
            dsbuttondialog.setSelected(false);
            itbuttondialog.setSelected(false);
            sebuttondialog.setSelected(false);
            ifbuttondialog.setSelected(false);
            jDialog1.setVisible(false);
            dispose();
            
            
        
    }//GEN-LAST:event_savebuttondialogActionPerformed

    private void NIMfielddialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIMfielddialogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIMfielddialogActionPerformed

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jframe2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jframe2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jframe2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jframe2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jframe2("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NIMfielddialog;
    private javax.swing.JButton deletebutton;
    private javax.swing.JRadioButton dsbuttondialog;
    private javax.swing.JButton editbutton;
    private javax.swing.JRadioButton ifbuttondialog;
    private javax.swing.JRadioButton itbuttondialog;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel10dialog;
    private javax.swing.JLabel jLabel8dialog;
    private javax.swing.JLabel jLabel9dialog;
    private javax.swing.JTextField namafielddialog;
    private javax.swing.JButton savebuttondialog;
    private javax.swing.JRadioButton sebuttondialog;
    // End of variables declaration//GEN-END:variables
}
